import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { IsLoginOpenProvider } from "./context/is-login-open";
import { UserProvider } from "./context/user-context";
import { SearchProvider } from "./context/search-context";
import { CategoryProvider } from "./context/category-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ConfiaMercado",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <IsLoginOpenProvider>
        <UserProvider>
          <SearchProvider>
            <CategoryProvider>
              <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
              >
                <div className="min-h-screen bg-white">
                  {children}
                  <Toaster />
                </div>
              </body>
            </CategoryProvider>
          </SearchProvider>
        </UserProvider>
      </IsLoginOpenProvider>
    </html>
  );
}
